#!/usr/bin/env node
// Regenerates modules/index.js from whatever operation files actually exist on disk, so adding a
// batch of ported ops never requires manually hand-editing a 500-line import list. Only touches
// modules/index.js itself; run after dropping new files into modules/<category>/*.js.
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const MODULES_DIR = fileURLToPath(new URL('../modules/', import.meta.url));

const categories = readdirSync(MODULES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const importLines = [];
for (const cat of categories) {
  const files = readdirSync(join(MODULES_DIR, cat))
    .filter((f) => f.endsWith('.js') && !f.startsWith('_'))
    .sort();
  for (const f of files) importLines.push(`import './${cat}/${f}';`);
}

const header = `// Imports every operation file so they self-register into the module registry.\n// Generated by tools/gen-index.mjs - do not hand-edit; re-run that script after adding op files.\n`;
writeFileSync(join(MODULES_DIR, 'index.js'), header + importLines.join('\n') + '\n');
console.log(`Wrote ${importLines.length} imports across ${categories.length} categories to modules/index.js`);
